#include <ErrNo.h>

enum {NO_ERROR, NO_FUNCTION, NO_FILE, NO_PATH, NO_HANDLE, NO_ACCESS, EDOM,
      ERANGE, EILSEQ, FOPEN, FFLUSH, FCLOSE, NO_MODE, FWRITE, FREAD, FSEEK,
      FTELL, FSIZE, FREMOVE, FRENAME, FTEMPNAME, FTEMPFILE};

int errno = 0;