main: main.o malloc.o ctype.o errno.o locale.o math.o setjmp.o signal.o file.o temp.o scanf.o printf.o stdlib.o time.o string.o printtest.o charactertest.o floattest.o limitstest.o asserttest.o stringtest.o localetest.o setjmptest.o mathtest.o filetest.o stdiotest.o signaltest.o stacktest.o malloctest.o stdlibtest.o timetest.o
	ld -o main main.o malloc.o ctype.o errno.o locale.o math.o setjmp.o signal.o file.o temp.o scanf.o printf.o stdlib.o time.o string.o printtest.o charactertest.o floattest.o limitstest.o asserttest.o stringtest.o localetest.o setjmptest.o mathtest.o filetest.o stdiotest.o signaltest.o stacktest.o malloctest.o stdlibtest.o timetest.o

main.o: main.asm
	nasm -f elf64 -o main.o main.asm

malloc.o: malloc.asm
	nasm -f elf64 -o malloc.o malloc.asm

ctype.o: ctype.asm
	nasm -f elf64 -o ctype.o ctype.asm

errno.o: errno.asm
	nasm -f elf64 -o errno.o errno.asm

locale.o: locale.asm
	nasm -f elf64 -o locale.o locale.asm

math.o: math.asm
	nasm -f elf64 -o math.o math.asm

setjmp.o: setjmp.asm
	nasm -f elf64 -o setjmp.o setjmp.asm

signal.o: signal.asm
	nasm -f elf64 -o signal.o signal.asm

file.o: file.asm
	nasm -f elf64 -o file.o file.asm

temp.o: temp.asm
	nasm -f elf64 -o temp.o temp.asm

scanf.o: scanf.asm
	nasm -f elf64 -o scanf.o scanf.asm

printf.o: printf.asm
	nasm -f elf64 -o printf.o printf.asm

stdlib.o: stdlib.asm
	nasm -f elf64 -o stdlib.o stdlib.asm

time.o: time.asm
	nasm -f elf64 -o time.o time.asm

string.o: string.asm
	nasm -f elf64 -o string.o string.asm

printtest.o: printtest.asm
	nasm -f elf64 -o printtest.o printtest.asm

charactertest.o: charactertest.asm
	nasm -f elf64 -o charactertest.o charactertest.asm

floattest.o: floattest.asm
	nasm -f elf64 -o floattest.o floattest.asm

limitstest.o: limitstest.asm
	nasm -f elf64 -o limitstest.o limitstest.asm

asserttest.o: asserttest.asm
	nasm -f elf64 -o asserttest.o asserttest.asm

stringtest.o: stringtest.asm
	nasm -f elf64 -o stringtest.o stringtest.asm

localetest.o: localetest.asm
	nasm -f elf64 -o localetest.o localetest.asm

setjmptest.o: setjmptest.asm
	nasm -f elf64 -o setjmptest.o setjmptest.asm

mathtest.o: mathtest.asm
	nasm -f elf64 -o mathtest.o mathtest.asm

filetest.o: filetest.asm
	nasm -f elf64 -o filetest.o filetest.asm

stdiotest.o: stdiotest.asm
	nasm -f elf64 -o stdiotest.o stdiotest.asm

signaltest.o: signaltest.asm
	nasm -f elf64 -o signaltest.o signaltest.asm

stacktest.o: stacktest.asm
	nasm -f elf64 -o stacktest.o stacktest.asm

malloctest.o: malloctest.asm
	nasm -f elf64 -o malloctest.o malloctest.asm

stdlibtest.o: stdlibtest.asm
	nasm -f elf64 -o stdlibtest.o stdlibtest.asm

timetest.o: timetest.asm
	nasm -f elf64 -o timetest.o timetest.asm

clear:
	rm main.o
	rm malloc.o
	rm ctype.o
	rm errno.o
	rm locale.o
	rm math.o
	rm setjmp.o
	rm signal.o
	rm file.o
	rm temp.o
	rm scanf.o
	rm printf.o
	rm stdlib.o
	rm time.o
	rm string.o
	rm printtest.o
	rm charactertest.o
	rm floattest.o
	rm limitstest.o
	rm asserttest.o
	rm stringtest.o
	rm localetest.o
	rm setjmptest.o
	rm mathtest.o
	rm filetest.o
	rm stdiotest.o
	rm signaltest.o
	rm stacktest.o
	rm malloctest.o
	rm stdlibtest.o
	rm timetest.o
	rm main
